SELECT
  'DECA' as Payment_Card_Type,
  'MSTR' as Payment_Card_Scheme,
  case when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ATM' then 'TATM'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'OTHER' then 'EPOS'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' then 'ECOM'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('MOTO' , 'MAIL') then 'MOTO'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL IS NULL then 'OTHR'
      else 'check the query'
  end as Terminal_Type,
  case when FCT.CARD_TRANSACTION_TYPE = 'PURCHASE' AND FCT.CARD_TRANSACTION_MMC_CODE = '6011' then 'CADV'  -- merchant_category_code is best way to identify cash advances
      when FCT.CARD_TRANSACTION_TYPE  = 'PURCHASE' then 'SALE'
      when FCT.CARD_TRANSACTION_TYPE  = 'ATM_CASH_WITHDRAWAL' then 'ATMW'
      when FCT.CARD_TRANSACTION_TYPE  = 'REFUND' then 'RFND'
      when FCT.CARD_TRANSACTION_TYPE  = 'ORIGINAL_CREDIT_TRANSFER' then 'OTHC'
      else 'check the query'
  end as Operation_Type,
  case when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' then 'RMTR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') AND FCT.CARD_TRANSACTION_PAN_ENTRY_MODE = 'CHIP_CONTACTLESS' then 'CNFC'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') then 'CNTR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL is null AND FCT.CARD_TRANSACTION_PIN_PRESENT = false then 'CNTR'
      else 'check the query' end as Initiation_Channel,
  case when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') then 'REM0'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' then 'REM1'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL IS NULL then 'REM0'
      else 'check the query'
    end as Initiation_subchannel,
  case when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND FCT.CARD_TRANSACTION_AUTHENTICATION_METHOD = 'CHALLENGE' AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'SUCCESSFUL' then 'SCA1'
      when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND FCT.CARD_TRANSACTION_AUTHENTICATION_METHOD = 'FRICTIONLESS' AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'EXEMPTED' then 'RLOW'
      when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_ACQUIRER_EXEMPTION = 'RECURRING_PAYMENT' then 'RETR'
when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'MERCHANT_INITIATED_TRANSACTION' then 'MITR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'TRANSACTION_RISK_ANALYSIS' then 'RTRA'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'SECURE_CORPORATE_PAYMENT' then 'SECO'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE'AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) then 'OTHR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') AND FCT.CARD_TRANSACTION_PAN_ENTRY_MODE = 'CHIP_CONTACTLESS' AND FCT.CARD_TRANSACTION_PIN_PRESENT = false then 'CLOW'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') AND FCT.CARD_TRANSACTION_PIN_PRESENT = true then 'SCA1'
      when FCT.CARD_TRANSACTION_PIN_PRESENT = false then 'OTHR'
      else 'check the query'
    end as SCA,
  'NOAP' as Fraud_Type,
  left(FCT.CARD_TRANSACTION_MERCHANT_COUNTRY_CODE,2) as Country_of_Acquirer,
  left(FCT.CARD_TRANSACTION_MERCHANT_COUNTRY_CODE,2) as Country_of_terminal,
  'VOLU' as metric,
  count(*) AS ReportedAmount,
  CURRENT_TIMESTAMP AS LOAD_TIMESTAMP,
  "{{period}}"  AS Period,
FROM {{ source('source_dwh_strp,F_CI_CARD_TRANSACTION_DECRYPTED') }}  FCT
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD') }} C on FCT.T_D_CI_CARD_TRANSACTION_DIM_KEY = C.T_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD_TRANSACTION') }} DCT on DCT.T_DIM_KEY = FCT.T_D_CI_CARD_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,F_CI_CARD_TRANSACTION_EVENT') }} FTE on FTE.T_D_CI_CARD_TRANSACTION_DIM_KEY = DCT.T_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD_TRANSACTION_EVENT') }} DTE on FTE.T_D_CI_CARD_TRANSACTION_EVENT_DIM_KEY = DTE.T_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD_PRODUCT_DECRYPTED') }} CP on C.T_D_CI_CARD_PRODUCT_DIM_KEY = CP.T_DIM_KEY
where FCT.CARD_TRANSACTION_CLEARED_AMOUNT > 0
AND  CP.CARD_PRODUCT_CARD_COUNTRY = '{{country_code}}'
AND  FTE.TRANSACTION_EVENT_USER_TRANSACTION_TIME >= TIMESTAMP(DATETIME( '{{period_time['begin_date']}}', '{{time_zone}}'))
AND  FTE.TRANSACTION_EVENT_USER_TRANSACTION_TIME < TIMESTAMP(DATETIME( '{{period_time['end_date']}}', '{{time_zone}}'))
GROUP BY 1,2,3,4,5,6,7,8,9,10,11

UNION ALL

SELECT
  'DECA' as Payment_Card_Type,
  'MSTR' as Payment_Card_Scheme,
  case when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ATM' then 'TATM'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'OTHER' then 'EPOS'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' then 'ECOM'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('MOTO' , 'MAIL') then 'MOTO'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL IS NULL then 'OTHR'
      else 'check the query'
  end as Terminal_Type,
  case when FCT.CARD_TRANSACTION_TYPE = 'PURCHASE' AND FCT.CARD_TRANSACTION_MMC_CODE = '6011' then 'CADV'  -- merchant_category_code is best way to identify cash advances
      when FCT.CARD_TRANSACTION_TYPE  = 'PURCHASE' then 'SALE'
      when FCT.CARD_TRANSACTION_TYPE  = 'ATM_CASH_WITHDRAWAL' then 'ATMW'
      when FCT.CARD_TRANSACTION_TYPE  = 'REFUND' then 'RFND'
      when FCT.CARD_TRANSACTION_TYPE  = 'ORIGINAL_CREDIT_TRANSFER' then 'OTHC'
      else 'check the query'
  end as Operation_Type,
  case when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' then 'RMTR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') AND FCT.CARD_TRANSACTION_PAN_ENTRY_MODE = 'CHIP_CONTACTLESS' then 'CNFC'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') then 'CNTR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL is null AND FCT.CARD_TRANSACTION_PIN_PRESENT = false then 'CNTR'
      else 'check the query' end as Initiation_Channel,
  case when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') then 'REM0'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' then 'REM1'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL IS NULL then 'REM0'
      else 'check the query'
    end as Initiation_subchannel,
  case when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND FCT.CARD_TRANSACTION_AUTHENTICATION_METHOD = 'CHALLENGE' AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'SUCCESSFUL' then 'SCA1'
      when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND FCT.CARD_TRANSACTION_AUTHENTICATION_METHOD = 'FRICTIONLESS' AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'EXEMPTED' then 'RLOW'
      when  FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_ACQUIRER_EXEMPTION = 'RECURRING_PAYMENT' then 'RETR'
when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'MERCHANT_INITIATED_TRANSACTION' then 'MITR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'TRANSACTION_RISK_ANALYSIS' then 'RTRA'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE' AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) AND FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS = 'SECURE_CORPORATE_PAYMENT' then 'SECO'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL = 'ECOMMERCE'AND (FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS in ('UNAVAILABLE','THREEDS_REQUESTER_SCA_EXEMPTION') or FCT.CARD_TRANSACTION_AUTHENTICATION_STATUS is null) then 'OTHR'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') AND FCT.CARD_TRANSACTION_PAN_ENTRY_MODE = 'CHIP_CONTACTLESS' AND FCT.CARD_TRANSACTION_PIN_PRESENT = false then 'CLOW'
      when FCT.CARD_TRANSACTION_PAYMENT_CHANNEL in ('OTHER','ATM') AND FCT.CARD_TRANSACTION_PIN_PRESENT = true then 'SCA1'
      when FCT.CARD_TRANSACTION_PIN_PRESENT = false then 'OTHR'
      else 'check the query'
    end as SCA,
  'NOAP' as Fraud_Type,
  left(FCT.CARD_TRANSACTION_MERCHANT_COUNTRY_CODE,2) as Country_of_Acquirer,
  left(FCT.CARD_TRANSACTION_MERCHANT_COUNTRY_CODE,2) as Country_of_terminal,
  'VALE' as metric,
  sum (coalesce(FCT.CARD_TRANSACTION_CLEARED_AMOUNT ,0)) + sum(coalesce(CARD_TRANSACTION_REFUNDED_AMOUNT,0)) as total_sum,
  CURRENT_TIMESTAMP AS LOAD_TIMESTAMP,
  "{{period}}"  AS Period,
FROM {{ source('source_dwh_strp,F_CI_CARD_TRANSACTION_DECRYPTED') }}  FCT
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD') }} C on FCT.T_D_CI_CARD_TRANSACTION_DIM_KEY = C.T_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD_TRANSACTION') }} DCT on DCT.T_DIM_KEY = FCT.T_D_CI_CARD_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,F_CI_CARD_TRANSACTION_EVENT') }} FTE on FTE.T_D_CI_CARD_TRANSACTION_DIM_KEY = DCT.T_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD_TRANSACTION_EVENT') }} DTE on FTE.T_D_CI_CARD_TRANSACTION_EVENT_DIM_KEY = DTE.T_DIM_KEY
LEFT JOIN {{ source('source_dwh_strp,D_CI_CARD_PRODUCT_DECRYPTED') }} CP on C.T_D_CI_CARD_PRODUCT_DIM_KEY = CP.T_DIM_KEY
where FCT.CARD_TRANSACTION_CLEARED_AMOUNT > 0
AND   CP.CARD_PRODUCT_CARD_COUNTRY = '{{country_code}}'
AND   FTE.TRANSACTION_EVENT_USER_TRANSACTION_TIME >= TIMESTAMP(DATETIME( '{{period_time['begin_date']}}', '{{time_zone}}'))
AND   FTE.TRANSACTION_EVENT_USER_TRANSACTION_TIME < TIMESTAMP(DATETIME( '{{period_time['end_date']}}', '{{time_zone}}'))
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
